# SPDX-License-Identifier: GPL

obj-m := droidmole.o
droidmole-y := dm_module.o

include $(src)/common/Kbuild
include $(src)/interception/Kbuild
include $(src)/arch/$(CONFIG_DROIDMOLE_ARCH)/Kbuild

ccflags-y += -I$(srctree)/$(src)/
ccflags-y += -I$(srctree)/$(src)/arch/$(CONFIG_DROIDMOLE_ARCH)/
