// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: agent.proto

package protocol

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState_EmulatorState int32

const (
	// The emulator failed to start.
	AgentState_ERROR AgentState_EmulatorState = 0
	// The emulator is off.
	AgentState_OFF AgentState_EmulatorState = 1
	// The emulator is booting.
	AgentState_STARTING AgentState_EmulatorState = 2
	// The emulator is running and adb has connected.
	AgentState_RUNNING AgentState_EmulatorState = 3
)

// Enum value maps for AgentState_EmulatorState.
var (
	AgentState_EmulatorState_name = map[int32]string{
		0: "ERROR",
		1: "OFF",
		2: "STARTING",
		3: "RUNNING",
	}
	AgentState_EmulatorState_value = map[string]int32{
		"ERROR":    0,
		"OFF":      1,
		"STARTING": 2,
		"RUNNING":  3,
	}
)

func (x AgentState_EmulatorState) Enum() *AgentState_EmulatorState {
	p := new(AgentState_EmulatorState)
	*p = x
	return p
}

func (x AgentState_EmulatorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState_EmulatorState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentState_EmulatorState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentState_EmulatorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState_EmulatorState.Descriptor instead.
func (AgentState_EmulatorState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0, 0}
}

type StreamDisplayRequest_FrameFormat int32

const (
	// 3 bytes per pixel.
	StreamDisplayRequest_RGB888 StreamDisplayRequest_FrameFormat = 0
	// VP8 codec. Uses intermediate frames.
	StreamDisplayRequest_VP8 StreamDisplayRequest_FrameFormat = 1
)

// Enum value maps for StreamDisplayRequest_FrameFormat.
var (
	StreamDisplayRequest_FrameFormat_name = map[int32]string{
		0: "RGB888",
		1: "VP8",
	}
	StreamDisplayRequest_FrameFormat_value = map[string]int32{
		"RGB888": 0,
		"VP8":    1,
	}
)

func (x StreamDisplayRequest_FrameFormat) Enum() *StreamDisplayRequest_FrameFormat {
	p := new(StreamDisplayRequest_FrameFormat)
	*p = x
	return p
}

func (x StreamDisplayRequest_FrameFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamDisplayRequest_FrameFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (StreamDisplayRequest_FrameFormat) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x StreamDisplayRequest_FrameFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamDisplayRequest_FrameFormat.Descriptor instead.
func (StreamDisplayRequest_FrameFormat) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3, 0}
}

type ShellStartRequest_ShellType int32

const (
	// Do not spawn a PTY
	ShellStartRequest_RAW ShellStartRequest_ShellType = 0
	// Spawn a PTY
	ShellStartRequest_PTY ShellStartRequest_ShellType = 1
)

// Enum value maps for ShellStartRequest_ShellType.
var (
	ShellStartRequest_ShellType_name = map[int32]string{
		0: "RAW",
		1: "PTY",
	}
	ShellStartRequest_ShellType_value = map[string]int32{
		"RAW": 0,
		"PTY": 1,
	}
)

func (x ShellStartRequest_ShellType) Enum() *ShellStartRequest_ShellType {
	p := new(ShellStartRequest_ShellType)
	*p = x
	return p
}

func (x ShellStartRequest_ShellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellStartRequest_ShellType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (ShellStartRequest_ShellType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x ShellStartRequest_ShellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellStartRequest_ShellType.Descriptor instead.
func (ShellStartRequest_ShellType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9, 0}
}

type ShellOutputResponse_ShellOutputChannel int32

const (
	// Stdout
	ShellOutputResponse_OUT ShellOutputResponse_ShellOutputChannel = 0
	// Stderr
	ShellOutputResponse_ERR ShellOutputResponse_ShellOutputChannel = 1
)

// Enum value maps for ShellOutputResponse_ShellOutputChannel.
var (
	ShellOutputResponse_ShellOutputChannel_name = map[int32]string{
		0: "OUT",
		1: "ERR",
	}
	ShellOutputResponse_ShellOutputChannel_value = map[string]int32{
		"OUT": 0,
		"ERR": 1,
	}
)

func (x ShellOutputResponse_ShellOutputChannel) Enum() *ShellOutputResponse_ShellOutputChannel {
	p := new(ShellOutputResponse_ShellOutputChannel)
	*p = x
	return p
}

func (x ShellOutputResponse_ShellOutputChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellOutputResponse_ShellOutputChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (ShellOutputResponse_ShellOutputChannel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x ShellOutputResponse_ShellOutputChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellOutputResponse_ShellOutputChannel.Descriptor instead.
func (ShellOutputResponse_ShellOutputChannel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13, 0}
}

// AgentState describes the current state of the agent process and the virtual machine being controlled.
type AgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state of the emulator.
	EmulatorState AgentState_EmulatorState `protobuf:"varint,1,opt,name=emulator_state,json=emulatorState,proto3,enum=AgentState_EmulatorState" json:"emulator_state,omitempty"`
	// The error message associated with the error state.
	EmulatorError *string `protobuf:"bytes,2,opt,name=emulator_error,json=emulatorError,proto3,oneof" json:"emulator_error,omitempty"`
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentState) GetEmulatorState() AgentState_EmulatorState {
	if x != nil {
		return x.EmulatorState
	}
	return AgentState_ERROR
}

func (x *AgentState) GetEmulatorError() string {
	if x != nil && x.EmulatorError != nil {
		return *x.EmulatorError
	}
	return ""
}

// Requests the emulator boots with the given configuration.
// Example Settings:
//
//	Ram: 2048 Cores: 1
//	Display 720x1280 320dpi
type StartEmulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Memory in MBs
	RamSize uint32 `protobuf:"varint,1,opt,name=ram_size,json=ramSize,proto3" json:"ram_size,omitempty"`
	// Number of cores.
	CoreCount uint32 `protobuf:"varint,2,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	// The DPI of the main display.
	LcdDensity uint32 `protobuf:"varint,3,opt,name=lcd_density,json=lcdDensity,proto3" json:"lcd_density,omitempty"`
	// The width of the main display.
	LcdWidth uint32 `protobuf:"varint,4,opt,name=lcd_width,json=lcdWidth,proto3" json:"lcd_width,omitempty"`
	// The height of the main display.
	LcdHeight uint32 `protobuf:"varint,5,opt,name=lcd_height,json=lcdHeight,proto3" json:"lcd_height,omitempty"`
}

func (x *StartEmulatorRequest) Reset() {
	*x = StartEmulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEmulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmulatorRequest) ProtoMessage() {}

func (x *StartEmulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmulatorRequest.ProtoReflect.Descriptor instead.
func (*StartEmulatorRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StartEmulatorRequest) GetRamSize() uint32 {
	if x != nil {
		return x.RamSize
	}
	return 0
}

func (x *StartEmulatorRequest) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdDensity() uint32 {
	if x != nil {
		return x.LcdDensity
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdWidth() uint32 {
	if x != nil {
		return x.LcdWidth
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdHeight() uint32 {
	if x != nil {
		return x.LcdHeight
	}
	return 0
}

// Requests the emulator exits.
type StopEmulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Kills the emulator without waiting.
	ForceExit bool `protobuf:"varint,1,opt,name=force_exit,json=forceExit,proto3" json:"force_exit,omitempty"`
}

func (x *StopEmulatorRequest) Reset() {
	*x = StopEmulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopEmulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEmulatorRequest) ProtoMessage() {}

func (x *StopEmulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEmulatorRequest.ProtoReflect.Descriptor instead.
func (*StopEmulatorRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StopEmulatorRequest) GetForceExit() bool {
	if x != nil {
		return x.ForceExit
	}
	return false
}

// Requests the display is streamed with the given configuration.
type StreamDisplayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The frame encoding format.
	Format StreamDisplayRequest_FrameFormat `protobuf:"varint,1,opt,name=format,proto3,enum=StreamDisplayRequest_FrameFormat" json:"format,omitempty"`
	// The maximum number of frames to encode per second.
	// Extra frames will be dropped, with the most recent frame encoded every 1/max_fps seconds.
	// Set to 0 to disable limit.
	MaxFps uint32 `protobuf:"varint,2,opt,name=max_fps,json=maxFps,proto3" json:"max_fps,omitempty"`
	// How often in milliseconds to encode a keyframe.
	// Set to 0 to only send when required. Not all formats use intermediate frames.
	KeyframeInterval uint32 `protobuf:"varint,3,opt,name=keyframe_interval,json=keyframeInterval,proto3" json:"keyframe_interval,omitempty"`
}

func (x *StreamDisplayRequest) Reset() {
	*x = StreamDisplayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDisplayRequest) ProtoMessage() {}

func (x *StreamDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDisplayRequest.ProtoReflect.Descriptor instead.
func (*StreamDisplayRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StreamDisplayRequest) GetFormat() StreamDisplayRequest_FrameFormat {
	if x != nil {
		return x.Format
	}
	return StreamDisplayRequest_RGB888
}

func (x *StreamDisplayRequest) GetMaxFps() uint32 {
	if x != nil {
		return x.MaxFps
	}
	return 0
}

func (x *StreamDisplayRequest) GetKeyframeInterval() uint32 {
	if x != nil {
		return x.KeyframeInterval
	}
	return 0
}

// A single display frame.
// Based on the format requested, this may not be a keyframe.
// A frame with zero width and height signifies the display is off. Clients should display a blank screen.
// The width and height can change on a keyframe, which can occur if the emulator is restarted with a different
// configuration.
type DisplayFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether this is a key frame. For some formats, this will always be true.
	Keyframe bool `protobuf:"varint,1,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	// The width of the frame.
	Width uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// The height of the frame.
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// The raw frame data.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DisplayFrame) Reset() {
	*x = DisplayFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayFrame) ProtoMessage() {}

func (x *DisplayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayFrame.ProtoReflect.Descriptor instead.
func (*DisplayFrame) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DisplayFrame) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *DisplayFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A single line in the syslog.
type SysLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw line.
	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *SysLogEntry) Reset() {
	*x = SysLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysLogEntry) ProtoMessage() {}

func (x *SysLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysLogEntry.ProtoReflect.Descriptor instead.
func (*SysLogEntry) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SysLogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// A input event
type InputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*InputRequest_Touch
	Event isInputRequest_Event `protobuf_oneof:"event"`
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (m *InputRequest) GetEvent() isInputRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *InputRequest) GetTouch() *TouchEvent {
	if x, ok := x.GetEvent().(*InputRequest_Touch); ok {
		return x.Touch
	}
	return nil
}

type isInputRequest_Event interface {
	isInputRequest_Event()
}

type InputRequest_Touch struct {
	Touch *TouchEvent `protobuf:"bytes,1,opt,name=touch,proto3,oneof"`
}

func (*InputRequest_Touch) isInputRequest_Event() {}

// A touch event
type TouchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique id to represent a pointer. Ids can be reused. Ids are shared amongst all connections.
	Identifier uint32 `protobuf:"varint,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Coords
	X uint32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	// Pointer device. A pressure of 0 must be sent to signal the event of the touch.
	Pressure   uint32 `protobuf:"varint,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	TouchMajor int32  `protobuf:"varint,5,opt,name=touch_major,json=touchMajor,proto3" json:"touch_major,omitempty"`
	TouchMinor int32  `protobuf:"varint,6,opt,name=touch_minor,json=touchMinor,proto3" json:"touch_minor,omitempty"`
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TouchEvent) GetIdentifier() uint32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *TouchEvent) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchEvent) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TouchEvent) GetPressure() uint32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *TouchEvent) GetTouchMajor() int32 {
	if x != nil {
		return x.TouchMajor
	}
	return 0
}

func (x *TouchEvent) GetTouchMinor() int32 {
	if x != nil {
		return x.TouchMinor
	}
	return 0
}

// An input message to the shell.
type ShellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ShellRequest_Start
	//	*ShellRequest_Stdin
	//	*ShellRequest_Resize
	Message isShellRequest_Message `protobuf_oneof:"message"`
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (m *ShellRequest) GetMessage() isShellRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ShellRequest) GetStart() *ShellStartRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ShellRequest) GetStdin() *ShellStdInRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

func (x *ShellRequest) GetResize() *ShellResizeRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Resize); ok {
		return x.Resize
	}
	return nil
}

type isShellRequest_Message interface {
	isShellRequest_Message()
}

type ShellRequest_Start struct {
	Start *ShellStartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ShellRequest_Stdin struct {
	Stdin *ShellStdInRequest `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ShellRequest_Resize struct {
	Resize *ShellResizeRequest `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ShellRequest_Start) isShellRequest_Message() {}

func (*ShellRequest_Stdin) isShellRequest_Message() {}

func (*ShellRequest_Resize) isShellRequest_Message() {}

// Requests the given command is spawned.
type ShellStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Shell type
	ShellType ShellStartRequest_ShellType `protobuf:"varint,1,opt,name=shell_type,json=shellType,proto3,enum=ShellStartRequest_ShellType" json:"shell_type,omitempty"`
	// The command to execute.
	// Specify no command to spawn an interactive shell.
	Command *string `protobuf:"bytes,2,opt,name=command,proto3,oneof" json:"command,omitempty"`
	// The "TERM=" environment value.
	TermType *string `protobuf:"bytes,3,opt,name=term_type,json=termType,proto3,oneof" json:"term_type,omitempty"`
}

func (x *ShellStartRequest) Reset() {
	*x = ShellStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStartRequest) ProtoMessage() {}

func (x *ShellStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStartRequest.ProtoReflect.Descriptor instead.
func (*ShellStartRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ShellStartRequest) GetShellType() ShellStartRequest_ShellType {
	if x != nil {
		return x.ShellType
	}
	return ShellStartRequest_RAW
}

func (x *ShellStartRequest) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *ShellStartRequest) GetTermType() string {
	if x != nil && x.TermType != nil {
		return *x.TermType
	}
	return ""
}

// Feeds data into the stdin stream of the shell.
type ShellStdInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw blob to feed in.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Whether to close the stdin after this blob.
	Close bool `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
}

func (x *ShellStdInRequest) Reset() {
	*x = ShellStdInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStdInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStdInRequest) ProtoMessage() {}

func (x *ShellStdInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStdInRequest.ProtoReflect.Descriptor instead.
func (*ShellStdInRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ShellStdInRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShellStdInRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

// Notifies the shell that the screen has changed size.
type ShellResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Characters
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Pixels
	Width  uint32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ShellResizeRequest) Reset() {
	*x = ShellResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResizeRequest) ProtoMessage() {}

func (x *ShellResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResizeRequest.ProtoReflect.Descriptor instead.
func (*ShellResizeRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ShellResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellResizeRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ShellResizeRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// An output message from the shell.
type ShellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ShellResponse_Output
	//	*ShellResponse_Exit
	Message isShellResponse_Message `protobuf_oneof:"message"`
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (m *ShellResponse) GetMessage() isShellResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ShellResponse) GetOutput() *ShellOutputResponse {
	if x, ok := x.GetMessage().(*ShellResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *ShellResponse) GetExit() *ShellExitResponse {
	if x, ok := x.GetMessage().(*ShellResponse_Exit); ok {
		return x.Exit
	}
	return nil
}

type isShellResponse_Message interface {
	isShellResponse_Message()
}

type ShellResponse_Output struct {
	Output *ShellOutputResponse `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ShellResponse_Exit struct {
	Exit *ShellExitResponse `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

func (*ShellResponse_Output) isShellResponse_Message() {}

func (*ShellResponse_Exit) isShellResponse_Message() {}

// The output from a shell.
type ShellOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel.
	Channel ShellOutputResponse_ShellOutputChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=ShellOutputResponse_ShellOutputChannel" json:"channel,omitempty"`
	// The raw blob.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShellOutputResponse) Reset() {
	*x = ShellOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOutputResponse) ProtoMessage() {}

func (x *ShellOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOutputResponse.ProtoReflect.Descriptor instead.
func (*ShellOutputResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ShellOutputResponse) GetChannel() ShellOutputResponse_ShellOutputChannel {
	if x != nil {
		return x.Channel
	}
	return ShellOutputResponse_OUT
}

func (x *ShellOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A notification that the shell has terminated.
type ShellExitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The exit code.
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ShellExitResponse) Reset() {
	*x = ShellExitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExitResponse) ProtoMessage() {}

func (x *ShellExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExitResponse.ProtoReflect.Descriptor instead.
func (*ShellExitResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ShellExitResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// A directory listing request
type ListDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The directory path to list files in.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// A directory listing response.
type ListDirectoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ListDirectoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ListDirectoryResponse) GetEntries() []*ListDirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// A entry in a directory listing.
type ListDirectoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The entry name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Stat of the file.
	//
	// Types that are assignable to Stat:
	//
	//	*ListDirectoryEntry_StatError
	//	*ListDirectoryEntry_StatValue
	Stat isListDirectoryEntry_Stat `protobuf_oneof:"stat"`
}

func (x *ListDirectoryEntry) Reset() {
	*x = ListDirectoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryEntry) ProtoMessage() {}

func (x *ListDirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryEntry.ProtoReflect.Descriptor instead.
func (*ListDirectoryEntry) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ListDirectoryEntry) GetStat() isListDirectoryEntry_Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (x *ListDirectoryEntry) GetStatError() uint32 {
	if x, ok := x.GetStat().(*ListDirectoryEntry_StatError); ok {
		return x.StatError
	}
	return 0
}

func (x *ListDirectoryEntry) GetStatValue() *FileStat {
	if x, ok := x.GetStat().(*ListDirectoryEntry_StatValue); ok {
		return x.StatValue
	}
	return nil
}

type isListDirectoryEntry_Stat interface {
	isListDirectoryEntry_Stat()
}

type ListDirectoryEntry_StatError struct {
	StatError uint32 `protobuf:"varint,2,opt,name=stat_error,json=statError,proto3,oneof"`
}

type ListDirectoryEntry_StatValue struct {
	StatValue *FileStat `protobuf:"bytes,3,opt,name=stat_value,json=statValue,proto3,oneof"`
}

func (*ListDirectoryEntry_StatError) isListDirectoryEntry_Stat() {}

func (*ListDirectoryEntry_StatValue) isListDirectoryEntry_Stat() {}

type FileStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dev   uint64 `protobuf:"varint,1,opt,name=dev,proto3" json:"dev,omitempty"`
	Ino   uint64 `protobuf:"varint,2,opt,name=ino,proto3" json:"ino,omitempty"`
	Mode  uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Nlink uint32 `protobuf:"varint,4,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Uid   uint32 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid   uint32 `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	Size  uint64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Atime int64  `protobuf:"varint,8,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime int64  `protobuf:"varint,9,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime int64  `protobuf:"varint,10,opt,name=ctime,proto3" json:"ctime,omitempty"`
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat.ProtoReflect.Descriptor instead.
func (*FileStat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FileStat) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *FileStat) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *FileStat) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileStat) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *FileStat) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileStat) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileStat) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStat) GetAtime() int64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *FileStat) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FileStat) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

// A file stat request.
type StatFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file to stat.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Whether to follow links.
	FollowLinks bool `protobuf:"varint,2,opt,name=follow_links,json=followLinks,proto3" json:"follow_links,omitempty"`
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatFileRequest) GetFollowLinks() bool {
	if x != nil {
		return x.FollowLinks
	}
	return false
}

// A file stat response.
type StatFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stat:
	//
	//	*StatFileResponse_StatError
	//	*StatFileResponse_StatValue
	Stat isStatFileResponse_Stat `protobuf_oneof:"stat"`
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (m *StatFileResponse) GetStat() isStatFileResponse_Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (x *StatFileResponse) GetStatError() uint32 {
	if x, ok := x.GetStat().(*StatFileResponse_StatError); ok {
		return x.StatError
	}
	return 0
}

func (x *StatFileResponse) GetStatValue() *FileStat {
	if x, ok := x.GetStat().(*StatFileResponse_StatValue); ok {
		return x.StatValue
	}
	return nil
}

type isStatFileResponse_Stat interface {
	isStatFileResponse_Stat()
}

type StatFileResponse_StatError struct {
	StatError uint32 `protobuf:"varint,1,opt,name=stat_error,json=statError,proto3,oneof"`
}

type StatFileResponse_StatValue struct {
	StatValue *FileStat `protobuf:"bytes,2,opt,name=stat_value,json=statValue,proto3,oneof"`
}

func (*StatFileResponse_StatError) isStatFileResponse_Stat() {}

func (*StatFileResponse_StatValue) isStatFileResponse_Stat() {}

// A file pull request.
type PullFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file path to pull.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PullFileRequest) Reset() {
	*x = PullFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileRequest) ProtoMessage() {}

func (x *PullFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileRequest.ProtoReflect.Descriptor instead.
func (*PullFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PullFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// A file pull response.
type PullFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Raw bytes from the file.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Whether the end oof the file has been reached.
	Last bool `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
}

func (x *PullFileResponse) Reset() {
	*x = PullFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFileResponse) ProtoMessage() {}

func (x *PullFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFileResponse.ProtoReflect.Descriptor instead.
func (*PullFileResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PullFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PullFileResponse) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// A file push request.
type PushFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*PushFileRequest_Start
	//	*PushFileRequest_Data
	//	*PushFileRequest_End
	Message isPushFileRequest_Message `protobuf_oneof:"message"`
}

func (x *PushFileRequest) Reset() {
	*x = PushFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileRequest) ProtoMessage() {}

func (x *PushFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileRequest.ProtoReflect.Descriptor instead.
func (*PushFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (m *PushFileRequest) GetMessage() isPushFileRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *PushFileRequest) GetStart() *PushFileStartRequest {
	if x, ok := x.GetMessage().(*PushFileRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *PushFileRequest) GetData() *PushFileDataRequest {
	if x, ok := x.GetMessage().(*PushFileRequest_Data); ok {
		return x.Data
	}
	return nil
}

func (x *PushFileRequest) GetEnd() *PushFileEndRequest {
	if x, ok := x.GetMessage().(*PushFileRequest_End); ok {
		return x.End
	}
	return nil
}

type isPushFileRequest_Message interface {
	isPushFileRequest_Message()
}

type PushFileRequest_Start struct {
	Start *PushFileStartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type PushFileRequest_Data struct {
	Data *PushFileDataRequest `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type PushFileRequest_End struct {
	End *PushFileEndRequest `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*PushFileRequest_Start) isPushFileRequest_Message() {}

func (*PushFileRequest_Data) isPushFileRequest_Message() {}

func (*PushFileRequest_End) isPushFileRequest_Message() {}

// A file push start request.
type PushFileStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file path to write to.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The mode to create the file with.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *PushFileStartRequest) Reset() {
	*x = PushFileStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileStartRequest) ProtoMessage() {}

func (x *PushFileStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileStartRequest.ProtoReflect.Descriptor instead.
func (*PushFileStartRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PushFileStartRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushFileStartRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// A file push data request.
type PushFileDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data to write to the file.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PushFileDataRequest) Reset() {
	*x = PushFileDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileDataRequest) ProtoMessage() {}

func (x *PushFileDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileDataRequest.ProtoReflect.Descriptor instead.
func (*PushFileDataRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *PushFileDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A file push end request.
type PushFileEndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The modified time to set.
	Mtime uint32 `protobuf:"varint,1,opt,name=mtime,proto3" json:"mtime,omitempty"`
}

func (x *PushFileEndRequest) Reset() {
	*x = PushFileEndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushFileEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileEndRequest) ProtoMessage() {}

func (x *PushFileEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileEndRequest.ProtoReflect.Descriptor instead.
func (*PushFileEndRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *PushFileEndRequest) GetMtime() uint32 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

var file_agent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0a, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x65, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x65, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x65,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x22, 0x3e, 0x0a, 0x0d, 0x45, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x65, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xad, 0x01, 0x0a, 0x14, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x63, 0x64, 0x5f, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x63, 0x64, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x63, 0x64, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6c, 0x63, 0x64, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x63, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x6c, 0x63, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x34, 0x0a, 0x13, 0x53, 0x74,
	0x6f, 0x70, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69, 0x74,
	0x22, 0xbb, 0x01, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x70, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x46, 0x70, 0x73, 0x12, 0x2b, 0x0a,
	0x11, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x0b, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x47, 0x42,
	0x38, 0x38, 0x38, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x50, 0x38, 0x10, 0x01, 0x22, 0x6c,
	0x0a, 0x0c, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b,
	0x53, 0x79, 0x73, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22,
	0x3c, 0x0a, 0x0c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x05, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xa6, 0x01,
	0x0a, 0x0a, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x5f, 0x6d, 0x61,
	0x6a, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x75, 0x63, 0x68,
	0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x5f, 0x6d,
	0x69, 0x6e, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x75, 0x63,
	0x68, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x64, 0x49, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12,
	0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xca, 0x01, 0x0a, 0x11, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x0a, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x22, 0x1d, 0x0a,
	0x09, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x41,
	0x57, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x54, 0x59, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3d, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53,
	0x74, 0x64, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x22, 0x6a, 0x0a, 0x12, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63,
	0x6f, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x74, 0x0a, 0x0d, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x65, 0x78, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x13, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x27, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x12, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x07, 0x0a, 0x03,
	0x4f, 0x55, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x52, 0x52, 0x10, 0x01, 0x22, 0x27,
	0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x46, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0xd2, 0x01, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x76, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x64, 0x65, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x48, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x67, 0x0a, 0x10, 0x53, 0x74, 0x61,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x74,
	0x61, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3a, 0x0a, 0x10, 0x50, 0x75, 0x6c,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6c, 0x61, 0x73, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x14, 0x50, 0x75, 0x73, 0x68,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x75, 0x73, 0x68,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x45,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x32,
	0xf6, 0x04, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x74, 0x6f,
	0x70, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x30, 0x01,
	0x12, 0x36, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x79, 0x73, 0x4c, 0x6f, 0x67,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x53, 0x79, 0x73, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x30, 0x01, 0x12, 0x32, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x0d,
	0x6c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x15, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x70, 0x75, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x50, 0x75, 0x6c, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x50, 0x75,
	0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x36, 0x0a, 0x08, 0x70, 0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData = file_agent_proto_rawDesc
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_rawDescData)
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []interface{}{
	(AgentState_EmulatorState)(0),               // 0: AgentState.EmulatorState
	(StreamDisplayRequest_FrameFormat)(0),       // 1: StreamDisplayRequest.FrameFormat
	(ShellStartRequest_ShellType)(0),            // 2: ShellStartRequest.ShellType
	(ShellOutputResponse_ShellOutputChannel)(0), // 3: ShellOutputResponse.ShellOutputChannel
	(*AgentState)(nil),                          // 4: AgentState
	(*StartEmulatorRequest)(nil),                // 5: StartEmulatorRequest
	(*StopEmulatorRequest)(nil),                 // 6: StopEmulatorRequest
	(*StreamDisplayRequest)(nil),                // 7: StreamDisplayRequest
	(*DisplayFrame)(nil),                        // 8: DisplayFrame
	(*SysLogEntry)(nil),                         // 9: SysLogEntry
	(*InputRequest)(nil),                        // 10: InputRequest
	(*TouchEvent)(nil),                          // 11: TouchEvent
	(*ShellRequest)(nil),                        // 12: ShellRequest
	(*ShellStartRequest)(nil),                   // 13: ShellStartRequest
	(*ShellStdInRequest)(nil),                   // 14: ShellStdInRequest
	(*ShellResizeRequest)(nil),                  // 15: ShellResizeRequest
	(*ShellResponse)(nil),                       // 16: ShellResponse
	(*ShellOutputResponse)(nil),                 // 17: ShellOutputResponse
	(*ShellExitResponse)(nil),                   // 18: ShellExitResponse
	(*ListDirectoryRequest)(nil),                // 19: ListDirectoryRequest
	(*ListDirectoryResponse)(nil),               // 20: ListDirectoryResponse
	(*ListDirectoryEntry)(nil),                  // 21: ListDirectoryEntry
	(*FileStat)(nil),                            // 22: FileStat
	(*StatFileRequest)(nil),                     // 23: StatFileRequest
	(*StatFileResponse)(nil),                    // 24: StatFileResponse
	(*PullFileRequest)(nil),                     // 25: PullFileRequest
	(*PullFileResponse)(nil),                    // 26: PullFileResponse
	(*PushFileRequest)(nil),                     // 27: PushFileRequest
	(*PushFileStartRequest)(nil),                // 28: PushFileStartRequest
	(*PushFileDataRequest)(nil),                 // 29: PushFileDataRequest
	(*PushFileEndRequest)(nil),                  // 30: PushFileEndRequest
	(*empty.Empty)(nil),                         // 31: google.protobuf.Empty
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: AgentState.emulator_state:type_name -> AgentState.EmulatorState
	1,  // 1: StreamDisplayRequest.format:type_name -> StreamDisplayRequest.FrameFormat
	11, // 2: InputRequest.touch:type_name -> TouchEvent
	13, // 3: ShellRequest.start:type_name -> ShellStartRequest
	14, // 4: ShellRequest.stdin:type_name -> ShellStdInRequest
	15, // 5: ShellRequest.resize:type_name -> ShellResizeRequest
	2,  // 6: ShellStartRequest.shell_type:type_name -> ShellStartRequest.ShellType
	17, // 7: ShellResponse.output:type_name -> ShellOutputResponse
	18, // 8: ShellResponse.exit:type_name -> ShellExitResponse
	3,  // 9: ShellOutputResponse.channel:type_name -> ShellOutputResponse.ShellOutputChannel
	21, // 10: ListDirectoryResponse.entries:type_name -> ListDirectoryEntry
	22, // 11: ListDirectoryEntry.stat_value:type_name -> FileStat
	22, // 12: StatFileResponse.stat_value:type_name -> FileStat
	28, // 13: PushFileRequest.start:type_name -> PushFileStartRequest
	29, // 14: PushFileRequest.data:type_name -> PushFileDataRequest
	30, // 15: PushFileRequest.end:type_name -> PushFileEndRequest
	31, // 16: AgentController.streamState:input_type -> google.protobuf.Empty
	5,  // 17: AgentController.startEmulator:input_type -> StartEmulatorRequest
	6,  // 18: AgentController.stopEmulator:input_type -> StopEmulatorRequest
	7,  // 19: AgentController.streamDisplay:input_type -> StreamDisplayRequest
	31, // 20: AgentController.streamSysLog:input_type -> google.protobuf.Empty
	10, // 21: AgentController.sendInput:input_type -> InputRequest
	12, // 22: AgentController.openShell:input_type -> ShellRequest
	19, // 23: AgentController.listDirectory:input_type -> ListDirectoryRequest
	23, // 24: AgentController.statFile:input_type -> StatFileRequest
	25, // 25: AgentController.pullFile:input_type -> PullFileRequest
	27, // 26: AgentController.pushFile:input_type -> PushFileRequest
	4,  // 27: AgentController.streamState:output_type -> AgentState
	31, // 28: AgentController.startEmulator:output_type -> google.protobuf.Empty
	31, // 29: AgentController.stopEmulator:output_type -> google.protobuf.Empty
	8,  // 30: AgentController.streamDisplay:output_type -> DisplayFrame
	9,  // 31: AgentController.streamSysLog:output_type -> SysLogEntry
	31, // 32: AgentController.sendInput:output_type -> google.protobuf.Empty
	16, // 33: AgentController.openShell:output_type -> ShellResponse
	20, // 34: AgentController.listDirectory:output_type -> ListDirectoryResponse
	24, // 35: AgentController.statFile:output_type -> StatFileResponse
	26, // 36: AgentController.pullFile:output_type -> PullFileResponse
	31, // 37: AgentController.pushFile:output_type -> google.protobuf.Empty
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEmulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopEmulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamDisplayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStdInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellExitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDirectoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDirectoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushFileEndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_agent_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*InputRequest_Touch)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ShellRequest_Start)(nil),
		(*ShellRequest_Stdin)(nil),
		(*ShellRequest_Resize)(nil),
	}
	file_agent_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_agent_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ShellResponse_Output)(nil),
		(*ShellResponse_Exit)(nil),
	}
	file_agent_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*ListDirectoryEntry_StatError)(nil),
		(*ListDirectoryEntry_StatValue)(nil),
	}
	file_agent_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*StatFileResponse_StatError)(nil),
		(*StatFileResponse_StatValue)(nil),
	}
	file_agent_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*PushFileRequest_Start)(nil),
		(*PushFileRequest_Data)(nil),
		(*PushFileRequest_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_rawDesc = nil
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
