// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: agent.proto

package protocol

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState_EmulatorState int32

const (
	// The emulator failed to start.
	AgentState_ERROR AgentState_EmulatorState = 0
	// The emulator is off.
	AgentState_OFF AgentState_EmulatorState = 1
	// The emulator is booting.
	AgentState_STARTING AgentState_EmulatorState = 2
	// The emulator is running and adb has connected.
	AgentState_RUNNING AgentState_EmulatorState = 3
)

// Enum value maps for AgentState_EmulatorState.
var (
	AgentState_EmulatorState_name = map[int32]string{
		0: "ERROR",
		1: "OFF",
		2: "STARTING",
		3: "RUNNING",
	}
	AgentState_EmulatorState_value = map[string]int32{
		"ERROR":    0,
		"OFF":      1,
		"STARTING": 2,
		"RUNNING":  3,
	}
)

func (x AgentState_EmulatorState) Enum() *AgentState_EmulatorState {
	p := new(AgentState_EmulatorState)
	*p = x
	return p
}

func (x AgentState_EmulatorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState_EmulatorState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentState_EmulatorState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentState_EmulatorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState_EmulatorState.Descriptor instead.
func (AgentState_EmulatorState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0, 0}
}

type StreamDisplayRequest_FrameFormat int32

const (
	// 3 bytes per pixel.
	StreamDisplayRequest_RGB888 StreamDisplayRequest_FrameFormat = 0
	// VP8 codec. Uses intermediate frames.
	StreamDisplayRequest_VP8 StreamDisplayRequest_FrameFormat = 1
)

// Enum value maps for StreamDisplayRequest_FrameFormat.
var (
	StreamDisplayRequest_FrameFormat_name = map[int32]string{
		0: "RGB888",
		1: "VP8",
	}
	StreamDisplayRequest_FrameFormat_value = map[string]int32{
		"RGB888": 0,
		"VP8":    1,
	}
)

func (x StreamDisplayRequest_FrameFormat) Enum() *StreamDisplayRequest_FrameFormat {
	p := new(StreamDisplayRequest_FrameFormat)
	*p = x
	return p
}

func (x StreamDisplayRequest_FrameFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamDisplayRequest_FrameFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (StreamDisplayRequest_FrameFormat) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x StreamDisplayRequest_FrameFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamDisplayRequest_FrameFormat.Descriptor instead.
func (StreamDisplayRequest_FrameFormat) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2, 0}
}

type ShellStartRequest_ShellType int32

const (
	// Do not spawn a PTY
	ShellStartRequest_RAW ShellStartRequest_ShellType = 0
	// Spawn a PTY
	ShellStartRequest_PTY ShellStartRequest_ShellType = 1
)

// Enum value maps for ShellStartRequest_ShellType.
var (
	ShellStartRequest_ShellType_name = map[int32]string{
		0: "RAW",
		1: "PTY",
	}
	ShellStartRequest_ShellType_value = map[string]int32{
		"RAW": 0,
		"PTY": 1,
	}
)

func (x ShellStartRequest_ShellType) Enum() *ShellStartRequest_ShellType {
	p := new(ShellStartRequest_ShellType)
	*p = x
	return p
}

func (x ShellStartRequest_ShellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellStartRequest_ShellType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (ShellStartRequest_ShellType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x ShellStartRequest_ShellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellStartRequest_ShellType.Descriptor instead.
func (ShellStartRequest_ShellType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8, 0}
}

type ShellOutputResponse_ShellOutputChannel int32

const (
	// Stdout
	ShellOutputResponse_OUT ShellOutputResponse_ShellOutputChannel = 0
	// Stderr
	ShellOutputResponse_ERR ShellOutputResponse_ShellOutputChannel = 1
)

// Enum value maps for ShellOutputResponse_ShellOutputChannel.
var (
	ShellOutputResponse_ShellOutputChannel_name = map[int32]string{
		0: "OUT",
		1: "ERR",
	}
	ShellOutputResponse_ShellOutputChannel_value = map[string]int32{
		"OUT": 0,
		"ERR": 1,
	}
)

func (x ShellOutputResponse_ShellOutputChannel) Enum() *ShellOutputResponse_ShellOutputChannel {
	p := new(ShellOutputResponse_ShellOutputChannel)
	*p = x
	return p
}

func (x ShellOutputResponse_ShellOutputChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellOutputResponse_ShellOutputChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (ShellOutputResponse_ShellOutputChannel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x ShellOutputResponse_ShellOutputChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellOutputResponse_ShellOutputChannel.Descriptor instead.
func (ShellOutputResponse_ShellOutputChannel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12, 0}
}

// AgentState describes the current state of the agent process and the virtual machine being controlled.
type AgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state of the emulator.
	EmulatorState AgentState_EmulatorState `protobuf:"varint,1,opt,name=emulator_state,json=emulatorState,proto3,enum=AgentState_EmulatorState" json:"emulator_state,omitempty"`
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentState) GetEmulatorState() AgentState_EmulatorState {
	if x != nil {
		return x.EmulatorState
	}
	return AgentState_ERROR
}

// Requests the emulator boots with the given configuration.
// Example Settings:
//
//	Ram: 2048 Cores: 1
//	Display 720x1280 320dpi
type StartEmulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Memory in MBs
	RamSize uint32 `protobuf:"varint,1,opt,name=ram_size,json=ramSize,proto3" json:"ram_size,omitempty"`
	// Number of cores.
	CoreCount uint32 `protobuf:"varint,2,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	// The DPI of the main display.
	LcdDensity uint32 `protobuf:"varint,3,opt,name=lcd_density,json=lcdDensity,proto3" json:"lcd_density,omitempty"`
	// The width of the main display.
	LcdWidth uint32 `protobuf:"varint,4,opt,name=lcd_width,json=lcdWidth,proto3" json:"lcd_width,omitempty"`
	// The height of the main display.
	LcdHeight uint32 `protobuf:"varint,5,opt,name=lcd_height,json=lcdHeight,proto3" json:"lcd_height,omitempty"`
}

func (x *StartEmulatorRequest) Reset() {
	*x = StartEmulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEmulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmulatorRequest) ProtoMessage() {}

func (x *StartEmulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmulatorRequest.ProtoReflect.Descriptor instead.
func (*StartEmulatorRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StartEmulatorRequest) GetRamSize() uint32 {
	if x != nil {
		return x.RamSize
	}
	return 0
}

func (x *StartEmulatorRequest) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdDensity() uint32 {
	if x != nil {
		return x.LcdDensity
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdWidth() uint32 {
	if x != nil {
		return x.LcdWidth
	}
	return 0
}

func (x *StartEmulatorRequest) GetLcdHeight() uint32 {
	if x != nil {
		return x.LcdHeight
	}
	return 0
}

// Requests the display is streamed with the given configuration.
type StreamDisplayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The frame encoding format.
	Format StreamDisplayRequest_FrameFormat `protobuf:"varint,1,opt,name=format,proto3,enum=StreamDisplayRequest_FrameFormat" json:"format,omitempty"`
	// The maximum number of frames to encode per second.
	// Extra frames will be dropped, with the most recent frame encoded every 1/max_fps seconds.
	// Set to 0 to disable limit.
	MaxFps uint32 `protobuf:"varint,2,opt,name=max_fps,json=maxFps,proto3" json:"max_fps,omitempty"`
	// How often in milliseconds to encode a keyframe.
	// Set to 0 to only send when required. Not all formats use intermediate frames.
	KeyframeInterval uint32 `protobuf:"varint,3,opt,name=keyframe_interval,json=keyframeInterval,proto3" json:"keyframe_interval,omitempty"`
}

func (x *StreamDisplayRequest) Reset() {
	*x = StreamDisplayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDisplayRequest) ProtoMessage() {}

func (x *StreamDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDisplayRequest.ProtoReflect.Descriptor instead.
func (*StreamDisplayRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDisplayRequest) GetFormat() StreamDisplayRequest_FrameFormat {
	if x != nil {
		return x.Format
	}
	return StreamDisplayRequest_RGB888
}

func (x *StreamDisplayRequest) GetMaxFps() uint32 {
	if x != nil {
		return x.MaxFps
	}
	return 0
}

func (x *StreamDisplayRequest) GetKeyframeInterval() uint32 {
	if x != nil {
		return x.KeyframeInterval
	}
	return 0
}

// A single display frame.
// Based on the format requested, this may not be a keyframe.
// A frame with zero width and height signifies the display is off. Clients should display a blank screen.
// The width and height can change on a keyframe, which can occur if the emulator is restarted with a different
// configuration.
type DisplayFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether this is a key frame. For some formats, this will always be true.
	Keyframe bool `protobuf:"varint,1,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	// The width of the frame.
	Width uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// The height of the frame.
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// The raw frame data.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DisplayFrame) Reset() {
	*x = DisplayFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayFrame) ProtoMessage() {}

func (x *DisplayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayFrame.ProtoReflect.Descriptor instead.
func (*DisplayFrame) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DisplayFrame) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *DisplayFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A single line in the syslog.
type SysLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw line.
	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *SysLogEntry) Reset() {
	*x = SysLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysLogEntry) ProtoMessage() {}

func (x *SysLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysLogEntry.ProtoReflect.Descriptor instead.
func (*SysLogEntry) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SysLogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type TouchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Touches []*Touch `protobuf:"bytes,1,rep,name=touches,proto3" json:"touches,omitempty"`
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TouchEvent) GetTouches() []*Touch {
	if x != nil {
		return x.Touches
	}
	return nil
}

type Touch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier int32 `protobuf:"varint,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	X          int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y          int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Pressure   int32 `protobuf:"varint,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	TouchMajor int32 `protobuf:"varint,5,opt,name=touch_major,json=touchMajor,proto3" json:"touch_major,omitempty"`
	TouchMinor int32 `protobuf:"varint,6,opt,name=touch_minor,json=touchMinor,proto3" json:"touch_minor,omitempty"`
}

func (x *Touch) Reset() {
	*x = Touch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Touch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touch) ProtoMessage() {}

func (x *Touch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touch.ProtoReflect.Descriptor instead.
func (*Touch) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Touch) GetIdentifier() int32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *Touch) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Touch) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Touch) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Touch) GetTouchMajor() int32 {
	if x != nil {
		return x.TouchMajor
	}
	return 0
}

func (x *Touch) GetTouchMinor() int32 {
	if x != nil {
		return x.TouchMinor
	}
	return 0
}

// An input message to the shell.
type ShellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ShellRequest_Start
	//	*ShellRequest_Stdin
	//	*ShellRequest_Resize
	Message isShellRequest_Message `protobuf_oneof:"message"`
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (m *ShellRequest) GetMessage() isShellRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ShellRequest) GetStart() *ShellStartRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ShellRequest) GetStdin() *ShellStdInRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

func (x *ShellRequest) GetResize() *ShellResizeRequest {
	if x, ok := x.GetMessage().(*ShellRequest_Resize); ok {
		return x.Resize
	}
	return nil
}

type isShellRequest_Message interface {
	isShellRequest_Message()
}

type ShellRequest_Start struct {
	Start *ShellStartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ShellRequest_Stdin struct {
	Stdin *ShellStdInRequest `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ShellRequest_Resize struct {
	Resize *ShellResizeRequest `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ShellRequest_Start) isShellRequest_Message() {}

func (*ShellRequest_Stdin) isShellRequest_Message() {}

func (*ShellRequest_Resize) isShellRequest_Message() {}

// Requests the given command is spawned.
type ShellStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Shell type
	ShellType ShellStartRequest_ShellType `protobuf:"varint,1,opt,name=shell_type,json=shellType,proto3,enum=ShellStartRequest_ShellType" json:"shell_type,omitempty"`
	// The command to execute.
	// Specify no command to spawn an interactive shell.
	Command *string `protobuf:"bytes,2,opt,name=command,proto3,oneof" json:"command,omitempty"`
	// The "TERM=" environment value.
	TermType *string `protobuf:"bytes,3,opt,name=term_type,json=termType,proto3,oneof" json:"term_type,omitempty"`
}

func (x *ShellStartRequest) Reset() {
	*x = ShellStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStartRequest) ProtoMessage() {}

func (x *ShellStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStartRequest.ProtoReflect.Descriptor instead.
func (*ShellStartRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ShellStartRequest) GetShellType() ShellStartRequest_ShellType {
	if x != nil {
		return x.ShellType
	}
	return ShellStartRequest_RAW
}

func (x *ShellStartRequest) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *ShellStartRequest) GetTermType() string {
	if x != nil && x.TermType != nil {
		return *x.TermType
	}
	return ""
}

// Feeds data into the stdin stream of the shell.
type ShellStdInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw blob to feed in.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Whether to close the stdin after this blob.
	Close bool `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
}

func (x *ShellStdInRequest) Reset() {
	*x = ShellStdInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellStdInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStdInRequest) ProtoMessage() {}

func (x *ShellStdInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStdInRequest.ProtoReflect.Descriptor instead.
func (*ShellStdInRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ShellStdInRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShellStdInRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

// Notifies the shell that the screen has changed size.
type ShellResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Characters
	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Pixels
	Width  uint32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ShellResizeRequest) Reset() {
	*x = ShellResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResizeRequest) ProtoMessage() {}

func (x *ShellResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResizeRequest.ProtoReflect.Descriptor instead.
func (*ShellResizeRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ShellResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellResizeRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ShellResizeRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// An output message from the shell.
type ShellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ShellResponse_Output
	//	*ShellResponse_Exit
	Message isShellResponse_Message `protobuf_oneof:"message"`
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (m *ShellResponse) GetMessage() isShellResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ShellResponse) GetOutput() *ShellOutputResponse {
	if x, ok := x.GetMessage().(*ShellResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *ShellResponse) GetExit() *ShellExitResponse {
	if x, ok := x.GetMessage().(*ShellResponse_Exit); ok {
		return x.Exit
	}
	return nil
}

type isShellResponse_Message interface {
	isShellResponse_Message()
}

type ShellResponse_Output struct {
	Output *ShellOutputResponse `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ShellResponse_Exit struct {
	Exit *ShellExitResponse `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

func (*ShellResponse_Output) isShellResponse_Message() {}

func (*ShellResponse_Exit) isShellResponse_Message() {}

// The output from a shell.
type ShellOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel.
	Channel ShellOutputResponse_ShellOutputChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=ShellOutputResponse_ShellOutputChannel" json:"channel,omitempty"`
	// The raw blob.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShellOutputResponse) Reset() {
	*x = ShellOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOutputResponse) ProtoMessage() {}

func (x *ShellOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOutputResponse.ProtoReflect.Descriptor instead.
func (*ShellOutputResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ShellOutputResponse) GetChannel() ShellOutputResponse_ShellOutputChannel {
	if x != nil {
		return x.Channel
	}
	return ShellOutputResponse_OUT
}

func (x *ShellOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A notification that the shell has terminated.
type ShellExitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The exit code.
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ShellExitResponse) Reset() {
	*x = ShellExitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExitResponse) ProtoMessage() {}

func (x *ShellExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExitResponse.ProtoReflect.Descriptor instead.
func (*ShellExitResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ShellExitResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

var file_agent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x65, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x65, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x0d, 0x45,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0xad, 0x01, 0x0a, 0x14,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x63, 0x64, 0x5f, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x63, 0x64, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x63, 0x64, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6c, 0x63, 0x64, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x63, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x6c, 0x63, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x14,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6d, 0x61, 0x78, 0x46, 0x70, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x6b, 0x65, 0x79, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x0b, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x47, 0x42, 0x38, 0x38, 0x38, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x56, 0x50, 0x38, 0x10, 0x01, 0x22, 0x6c, 0x0a, 0x0c, 0x44, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65, 0x79,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x54, 0x6f,
	0x75, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x6f, 0x75, 0x63,
	0x68, 0x52, 0x07, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x05, 0x54,
	0x6f, 0x75, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x75, 0x63, 0x68, 0x5f, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x22, 0xa0,
	0x01, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x73,
	0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x53, 0x74, 0x64, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xca, 0x01, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x53, 0x68, 0x65, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x88, 0x01, 0x01, 0x22, 0x1d, 0x0a, 0x09, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x41, 0x57, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50,
	0x54, 0x59, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3d,
	0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x74, 0x64, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x22, 0x6a, 0x0a,
	0x12, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x74, 0x0a, 0x0d, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x65, 0x78,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x65, 0x78, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x94, 0x01, 0x0a, 0x13, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26,
	0x0a, 0x12, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x45, 0x52, 0x52, 0x10, 0x01, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45,
	0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32,
	0xda, 0x02, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x30, 0x01, 0x12, 0x36, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x79, 0x73, 0x4c,
	0x6f, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x53, 0x79, 0x73,
	0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0b, 0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData = file_agent_proto_rawDesc
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_rawDescData)
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_proto_goTypes = []interface{}{
	(AgentState_EmulatorState)(0),               // 0: AgentState.EmulatorState
	(StreamDisplayRequest_FrameFormat)(0),       // 1: StreamDisplayRequest.FrameFormat
	(ShellStartRequest_ShellType)(0),            // 2: ShellStartRequest.ShellType
	(ShellOutputResponse_ShellOutputChannel)(0), // 3: ShellOutputResponse.ShellOutputChannel
	(*AgentState)(nil),                          // 4: AgentState
	(*StartEmulatorRequest)(nil),                // 5: StartEmulatorRequest
	(*StreamDisplayRequest)(nil),                // 6: StreamDisplayRequest
	(*DisplayFrame)(nil),                        // 7: DisplayFrame
	(*SysLogEntry)(nil),                         // 8: SysLogEntry
	(*TouchEvent)(nil),                          // 9: TouchEvent
	(*Touch)(nil),                               // 10: Touch
	(*ShellRequest)(nil),                        // 11: ShellRequest
	(*ShellStartRequest)(nil),                   // 12: ShellStartRequest
	(*ShellStdInRequest)(nil),                   // 13: ShellStdInRequest
	(*ShellResizeRequest)(nil),                  // 14: ShellResizeRequest
	(*ShellResponse)(nil),                       // 15: ShellResponse
	(*ShellOutputResponse)(nil),                 // 16: ShellOutputResponse
	(*ShellExitResponse)(nil),                   // 17: ShellExitResponse
	(*empty.Empty)(nil),                         // 18: google.protobuf.Empty
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: AgentState.emulator_state:type_name -> AgentState.EmulatorState
	1,  // 1: StreamDisplayRequest.format:type_name -> StreamDisplayRequest.FrameFormat
	10, // 2: TouchEvent.touches:type_name -> Touch
	12, // 3: ShellRequest.start:type_name -> ShellStartRequest
	13, // 4: ShellRequest.stdin:type_name -> ShellStdInRequest
	14, // 5: ShellRequest.resize:type_name -> ShellResizeRequest
	2,  // 6: ShellStartRequest.shell_type:type_name -> ShellStartRequest.ShellType
	16, // 7: ShellResponse.output:type_name -> ShellOutputResponse
	17, // 8: ShellResponse.exit:type_name -> ShellExitResponse
	3,  // 9: ShellOutputResponse.channel:type_name -> ShellOutputResponse.ShellOutputChannel
	18, // 10: AgentController.streamState:input_type -> google.protobuf.Empty
	5,  // 11: AgentController.startEmulator:input_type -> StartEmulatorRequest
	6,  // 12: AgentController.streamDisplay:input_type -> StreamDisplayRequest
	18, // 13: AgentController.streamSysLog:input_type -> google.protobuf.Empty
	9,  // 14: AgentController.sendInput:input_type -> TouchEvent
	11, // 15: AgentController.openShell:input_type -> ShellRequest
	4,  // 16: AgentController.streamState:output_type -> AgentState
	18, // 17: AgentController.startEmulator:output_type -> google.protobuf.Empty
	7,  // 18: AgentController.streamDisplay:output_type -> DisplayFrame
	8,  // 19: AgentController.streamSysLog:output_type -> SysLogEntry
	18, // 20: AgentController.sendInput:output_type -> google.protobuf.Empty
	15, // 21: AgentController.openShell:output_type -> ShellResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEmulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamDisplayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Touch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellStdInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellExitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_agent_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ShellRequest_Start)(nil),
		(*ShellRequest_Stdin)(nil),
		(*ShellRequest_Resize)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_agent_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ShellResponse_Output)(nil),
		(*ShellResponse_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_rawDesc = nil
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
