[package]
name = "device-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
anyhow = "1.0"
frida = { path = "../frida-rust/frida" }

[dependencies.nix]
version = "0.26.2"
features = ["ptrace", "process"]
